import { chromium } from 'playwright-core';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const out=path.resolve('artifacts/qa');fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync),headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const context=await browser.newContext({viewport:{width:1440,height:900},recordVideo:{dir:out,size:{width:1280,height:800}}});
const page=await context.newPage(),errors=[],checks=[];
page.on('pageerror',e=>{errors.push(String(e));console.error(e);});page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push('HTTP '+r.status()+' '+r.url());});
async function state(){return page.evaluate(()=>kino.debug.getState());}
async function snap(name){await page.screenshot({path:path.join(out,name+'.png')});fs.writeFileSync(path.join(out,name+'.json'),JSON.stringify(await state(),null,2));}
function pass(name,detail){checks.push({name,passed:true,detail});console.log('PASS',name,detail??'');}
async function fresh(){await page.evaluate(()=>{kino.debug.reset();kino.debug.setActive(true);kino.debug.setInvulnerable(true);});}
async function station(predicate){const e=await page.evaluate(predicate);assert(e,'interaction entity exists');await page.evaluate(p=>{kino.debug.teleportPlayer(p);kino.debug.step(.45);},e.position);return e;}
async function use(){await page.keyboard.press('KeyF');await page.waitForTimeout(50);await page.evaluate(()=>{const s=kino.debug.getState();if(s.drinking)kino.debug.step(s.drinkLeft+.5);});return state();}
try{
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'load'});await page.waitForFunction(()=>kino?.debug.getState().ready,null,{timeout:120000});
 await snap('01-menu');await page.click('#start');await page.waitForFunction(()=>kino.debug.getState().active);pass('Start button captures the pointer and starts gameplay');
 await page.evaluate(()=>kino.debug.setInvulnerable(true));
 let before=await state();await page.keyboard.down('KeyD');await page.waitForTimeout(800);await page.keyboard.up('KeyD');let after=await state();
 assert(Math.hypot(after.player.feet[0]-before.player.feet[0],after.player.feet[2]-before.player.feet[2])>30);await snap('02-movement');pass('WASD movement with grounded collision',after.player.feet);
 await fresh();await page.evaluate(()=>kino.debug.step(17));after=await state();assert.equal(after.spawned,6);assert.equal(after.enemies.length,6);assert(after.enemies.some(z=>z.state==='chase'));await snap('03-round');pass('Six original round-one spawns tear barricades and pursue',after.enemies.map(z=>z.state));
 await fresh();const enemyId=await page.evaluate(()=>{kino.debug.teleportPlayer([0,100,1120]);kino.debug.step(.6);const p=kino.debug.getState().player.feet;const id=kino.debug.spawnEnemy([p[0],p[1],p[2]-115]);kino.debug.step(.05);kino.debug.aimAtEnemy(id);return id;});
 await page.mouse.down();await page.waitForTimeout(40);await page.mouse.up();await page.waitForTimeout(180);after=await state();assert.equal(after.weapon.mag,7);const hitEnemy=after.enemies.find(z=>z.id===enemyId);assert(!hitEnemy||hitEnemy.health<150);pass('Real mouse click spends ammunition and damages aimed zombie');
 for(let shot=0;shot<5&&(await state()).enemies.some(z=>z.id===enemyId);shot++){await page.evaluate(id=>kino.debug.aimAtEnemy(id),enemyId);await page.mouse.down();await page.waitForTimeout(40);await page.mouse.up();await page.waitForTimeout(180);}
 after=await state();assert(after.kills>=1);assert(after.points>500);await snap('04-combat');pass('Headshots kill and award points',after.points);
 const spent=8-after.weapon.mag;await page.keyboard.press('KeyR');await page.evaluate(()=>kino.debug.step(2));after=await state();assert.equal(after.weapon.mag,8);assert.equal(after.weapon.reserve,32-spent);pass('Reload transfers reserve ammunition');
 await fresh();await station(()=>kino.debug.getEntities().find(e=>e.targetname==='zombie_door'&&e.target==='foyer_bottom_door'));before=await state();after=await use();assert.equal(after.points,500);assert(!after.openDoors.includes('foyer_bottom_door'));pass('Door rejects insufficient funds without spending');
 await page.evaluate(()=>kino.debug.grantPoints(1000));await snap('05-door-closed');after=await use();assert(after.openDoors.includes('foyer_bottom_door'));assert.equal(after.points,750);await snap('06-door-open');pass('Door purchase changes collision, navigation, and visuals');
 await fresh();await station(()=>kino.debug.getEntities().find(e=>e.script_noteworthy==='specialty_quickrevive'));after=await use();assert(after.perks.includes('specialty_quickrevive'));assert.equal(after.points,0);
 await page.evaluate(()=>{kino.debug.setInvulnerable(false);kino.debug.damagePlayer(100);kino.debug.step(4.1);});after=await state();assert.equal(after.health,100);assert(!after.perks.includes('specialty_quickrevive'));await snap('07-revive');pass('Purchased Quick Revive consumes perk and revives');
 await fresh();await page.evaluate(()=>kino.debug.grantPoints(100000));
 const doors=(await state()).doors.filter(d=>d.flag);
 for(const d of doors){await page.evaluate(p=>{kino.debug.teleportPlayer(p);kino.debug.step(.45);},d.triggers[0]);await use();}
 await station(()=>kino.debug.getEntities().find(e=>e.targetname==='use_elec_switch'));after=await use();assert(after.power);await snap('08-power');pass('Power activates and opens electric doors');
 const route=await page.evaluate(()=>kino.debug.navigationPath([-115,72,1254],[-488,0,-1246]));console.log('STAGE ROUTE',route);
 assert(route.length>2);assert(Math.hypot(route.at(-1)[0]+488,route.at(-1)[2]+1246)<110);pass('Navigation connects lobby to stage through purchased route',route.length);
 await station(()=>kino.debug.getEntities().find(e=>e.targetname==='weapon_upgrade'&&e.zombie_weapon_upgrade==='mp40_zm'));after=await use();assert.equal(after.weapon.id,'mp40_zm');pass('Original MP40 wall-buy gives second weapon');
 await page.waitForFunction(()=>kino.debug.getState().viewmodelReady&&kino.debug.weaponVisual().mode==='idle',null,{timeout:30000});const autoAmmo=(await state()).weapon.mag;await page.mouse.down();await page.waitForFunction(ammo=>kino.debug.getState().weapon.mag<ammo-1,autoAmmo,{timeout:5000});await page.mouse.up();after=await state();assert(after.weapon.mag<autoAmmo-1);await snap('09-mp40');pass('Automatic fire uses original weapon cadence');
 await station(()=>kino.debug.getEntities().find(e=>e.script_noteworthy==='specialty_armorvest'));after=await use();assert.equal(after.maxHealth,250);assert.equal(after.health,250);pass('Juggernog increases health after power');
 await station(()=>kino.debug.getEntities().find(e=>e.targetname==='trigger_teleport_pad_0'));after=await use();assert.equal(after.teleporter,'linking');
 await station(()=>kino.debug.getEntities().find(e=>e.targetname==='pf16_auto1'&&e.classname==='trigger_use'));after=await use();assert.equal(after.teleporter,'linked');
 await station(()=>kino.debug.getEntities().find(e=>e.targetname==='trigger_teleport_pad_0'));await use();await page.evaluate(()=>kino.debug.step(2.1));after=await state();assert(after.player.feet[1]>300);await snap('10-projection');pass('Two-pad link and teleport reach the projection room',after.player.feet);
 await station(()=>kino.debug.getEntities().find(e=>e.targetname==='zombie_vending_upgrade'));after=await use();assert(after.pack);assert(!after.weapon.upgraded);await page.evaluate(()=>kino.debug.step(4.5));after=await use();assert(after.weapon.upgraded);pass('Pack-a-Punch processes and returns the upgraded weapon');
 await page.evaluate(()=>kino.debug.step(38));after=await state();assert(after.player.feet[2]>1000);await snap('11-return');pass('Teleporter returns safely after projection and optional hidden room');
 await fresh();await page.evaluate(()=>{kino.debug.setRound(5);kino.debug.step(16);});after=await state();assert(after.enemies.length>0);await snap('12-later-round');pass('Later rounds continue with scaled enemies');
 await fresh();await page.evaluate(()=>{kino.debug.step(.6);const p=kino.debug.getState().player.feet;const id=kino.debug.spawnEnemy([p[0],p[1],p[2]-120],'dog');kino.debug.step(.1);kino.debug.aimAtEnemy(id);});await snap('13-hellhound');pass('Original hellhound model and animation load');
 await fresh();await page.evaluate(()=>{kino.debug.teleportPlayer([0,100,1120]);kino.debug.step(.6);const p=kino.debug.getState().player.feet;const id=kino.debug.spawnEnemy([p[0],p[1],p[2]-130],'nova');kino.debug.step(.1);kino.debug.aimAtEnemy(id);});await snap('13b-nova');after=await state();assert.equal(after.enemies[0].health,112);assert.equal(after.enemies[0].animation,'walk');
 for(let i=0;i<6&&(await state()).enemies.length;i++){await page.evaluate(()=>{const z=kino.debug.getState().enemies[0];if(z)kino.debug.aimAtEnemy(z.id);});await page.mouse.down();await page.waitForTimeout(40);await page.mouse.up();await page.waitForTimeout(180);}
 assert.equal((await page.evaluate(()=>kino.debug.specialState())).gasClouds,1);await snap('13c-gas');await page.evaluate(()=>kino.debug.step(7.2));assert.equal((await page.evaluate(()=>kino.debug.specialState())).gasClouds,0);pass('Nova crawler uses native rig, 75% health, and seven-second gas cloud');
 await fresh();await page.evaluate(()=>kino.debug.grantPoints(10000));await station(()=>kino.debug.getEntities().find(e=>e.id===kino.debug.specialState().boxLocation));await use();await page.evaluate(()=>kino.debug.step(4.1));let special=await page.evaluate(()=>kino.debug.specialState());assert(special.box.ready);const boxWeapon=special.box.weapon;after=await use();if(boxWeapon==='zombie_cymbal_monkey')assert.equal(after.monkeys,3);else assert.equal(after.weapon.id,boxWeapon);await page.waitForFunction(()=>kino.debug.getState().viewmodelReady);await snap('13d-mystery-box');pass('Mystery Box charges, rolls, and grants its offered weapon',boxWeapon);
 await fresh();await page.evaluate(()=>{kino.debug.teleportPlayer([0,100,1120]);kino.debug.step(.6);kino.debug.giveWeapon('ray_gun_zm');});await page.waitForFunction(()=>kino.debug.getState().viewmodelReady);await page.waitForFunction(()=>kino.debug.weaponVisual().mode==='idle');await page.evaluate(()=>{const p=kino.debug.getState().player.feet;const id=kino.debug.spawnEnemy([p[0],p[1],p[2]-160]);kino.debug.step(.1);kino.debug.aimAtEnemy(id);});await page.mouse.down();await page.waitForTimeout(40);await page.mouse.up();await page.evaluate(()=>kino.debug.step(.3));after=await state();assert(after.kills>=1);assert.equal(after.weapon.mag,19);await snap('13e-ray-gun');pass('Ray Gun hits and applies native explosive weapon damage');
 await fresh();const fragments=await page.evaluate(()=>kino.debug.getEntities().filter(e=>e.targetname==='meteor_egg_trigger'));
 for(const e of fragments){await page.evaluate(p=>{kino.debug.teleportPlayer(p);kino.debug.step(.45);},e.position);await use();}
 assert.equal((await page.evaluate(()=>kino.debug.specialState())).meteors,3);await page.waitForFunction(()=>kino.debug.audioState().played.includes('115'),null,{timeout:15000});pass('All three native fragment triggers play the original 115 track');
 const audio=await page.evaluate(()=>kino.debug.audioState());assert(audio.nativeCues>=19);assert(audio.played.includes('round'));pass('Browser decodes and plays native T5 audio',audio.decoded);
 await fresh();await page.evaluate(()=>{kino.debug.setInvulnerable(false);kino.debug.damagePlayer(100);});after=await state();assert.equal(after.phase,'gameover');assert(!after.active);await snap('14-gameover');await page.click('#start');after=await state();assert.equal(after.round,1);assert.equal(after.health,100);assert.equal(after.points,500);pass('Game-over screen restarts a clean run');
 assert.equal(errors.length,0,errors.join('\n'));
}catch(e){checks.push({name:'Failure',passed:false,error:String(e),stack:e.stack,lastShot:await page.evaluate(()=>kino.debug.lastShot())});console.error(e);console.log('LAST SHOT',await page.evaluate(()=>kino.debug.lastShot()));await snap('failure');process.exitCode=1;}
finally{const report={checks,errors,state:await state().catch(()=>null)};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log('CHECKS',checks.length,'ERRORS',errors.length);await context.close();await browser.close();}
