import {chromium} from 'playwright-core';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const out='artifacts/zombies';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}}),checks=[],errors=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
const state=()=>page.evaluate(()=>kino.debug.getState()),special=()=>page.evaluate(()=>kino.debug.specialState());
const step=n=>page.evaluate(n=>kino.debug.step(n),n);
const fresh=async()=>{await page.evaluate(()=>{kino.debug.reset();kino.debug.setActive(true);kino.debug.setInvulnerable(true);kino.debug.teleportPlayer([0,100,1120]);kino.debug.step(.6);});await page.waitForFunction(()=>kino.debug.getState().viewmodelReady);await step(.6);};
async function freeze(name){await page.evaluate(()=>{kino.debug.pause();document.getElementById('menu').hidden=true;document.body.classList.remove('menu-open');});await page.screenshot({path:out+'/'+name+'.png'});await page.evaluate(()=>kino.debug.setActive(true));await page.waitForFunction(()=>kino.debug.audioState().state==='running');}
function pass(name,detail){checks.push({name,passed:true,detail});console.log('PASS',name);}
async function station(predicate){const e=await page.evaluate(predicate);assert(e);await page.evaluate(p=>kino.debug.teleportPlayer(p),e.position);return e;}
try{
 await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>kino?.debug.getState().ready,null,{timeout:120000});await page.click('#start');await fresh();
 const definitions=await page.evaluate(()=>fetch('game-data.json').then(r=>r.json()));
 for(const perk of Object.keys(definitions.perkDrinks)){
  await fresh();await page.evaluate(()=>kino.debug.grantPoints(20000));await station(()=>kino.debug.getEntities().find(e=>e.targetname==='use_elec_switch'));await page.evaluate(()=>kino.debug.interact());
  const e=await page.evaluate(id=>kino.debug.getEntities().find(e=>e.script_noteworthy===id),perk);
  await page.evaluate(e=>{kino.debug.teleportPlayer(e.position);kino.debug.interact();kino.debug.teleportPlayer([0,100,1120]);kino.debug.lookAt([0,140,800]);},e);
  let s=await state();assert.equal(s.drinking,perk);assert(!s.perks.includes(perk));const mag=s.weapon.mag,grenades=s.grenades;
  assert.equal(await page.evaluate(()=>kino.debug.shoot()),false);assert.equal(await page.evaluate(()=>kino.debug.melee()),false);await page.keyboard.press('KeyG');await page.keyboard.press('KeyQ');await page.keyboard.press('KeyR');
  await step(.75);assert.equal((await state()).weapon.mag,mag);assert.equal((await state()).grenades,grenades);assert((await special()).drink);await freeze('drink-'+perk);
  await step(3.4);s=await state();assert(s.perks.includes(perk));assert.equal(s.drinking,null);assert.equal((await special()).drink,null);await step(.6);assert.equal(await page.evaluate(()=>kino.debug.shoot()),true);
  pass('Native bottle animation, action lock, perk grant and weapon recovery: '+perk);
 }
 await page.waitForFunction(()=>kino.debug.audioState().played.some(k=>k.endsWith('/swallowmn_00')));const played=await page.evaluate(()=>kino.debug.audioState().played);assert(played.some(k=>k.endsWith('/openmn_00')));assert(played.some(k=>k.endsWith('/breakmn_00')));pass('Bottle notifies play native opening, swallowing and breaking sounds');
 await fresh();await station(()=>kino.debug.getEntities().find(e=>e.script_noteworthy==='specialty_quickrevive'));await page.evaluate(()=>{kino.debug.interact();kino.debug.setInvulnerable(false);kino.debug.damagePlayer(100);});assert.equal((await special()).drink,null);assert.equal((await state()).phase,'gameover');pass('Downing interrupts bottle animation without awarding the perk');
 await fresh();await page.evaluate(()=>{const p=kino.debug.getState().player.feet;kino.debug.grantScore(2001);const id=kino.debug.spawnEnemy([p[0],p[1],p[2]-160]);kino.debug.damageEnemy(id);});let drops=(await special()).pickups;assert.equal(drops.length,1);assert(!['nuke','fire_sale','carpenter'].includes(drops[0].type));assert.equal((await state()).dropCount,1);pass('A real zombie death produces the score-triggered native pickup');
 await fresh();await page.evaluate(()=>{const p=kino.debug.getState().player.feet;Object.keys({full_ammo:1,insta_kill:1,double_points:1,nuke:1,carpenter:1,fire_sale:1}).forEach((k,i)=>kino.debug.dropPowerup(k,[p[0]-150+i*60,p[1]+35,p[2]-200]));kino.debug.lookAt([p[0],p[1]+65,p[2]-200]);});await freeze('all-powerups');assert.equal((await special()).pickups.length,6);await step(15.1);assert((await special()).pickups.every(p=>p.age>=15));await step(12);assert.equal((await special()).pickups.length,0);pass('All six original models load, animate, flash and expire');
 await fresh();await page.evaluate(()=>{kino.debug.shoot();const p=kino.debug.getState().player.feet;kino.debug.dropPowerup('full_ammo',p);});await step(.1);let s=await state();assert.equal(s.weapon.mag,7);assert.equal(s.weapon.reserve,80);assert.equal((await special()).pickups.length,0);await page.waitForFunction(()=>kino.debug.audioState().played.includes('full_ammo'));pass('Walking into Max Ammo refills reserve, preserves the magazine and plays its announcer');
 await fresh();await page.evaluate(()=>{const s=kino.debug.getState();for(const b of s.barriers.slice(0,6))kino.debug.setBoards(b.id,0);kino.debug.dropPowerup('carpenter',s.player.feet);});await step(.1);assert((await state()).barriers.every(b=>b.count>0));assert.equal((await state()).points,700);pass('Carpenter pickup restores barricades and awards 200 points');
 await fresh();await page.evaluate(()=>{const p=kino.debug.getState().player.feet;for(const k of ['double_points','insta_kill','fire_sale'])kino.debug.dropPowerup(k,p);});await step(.1);s=await state();assert(s.effects.double_points>s.time&&s.effects.insta_kill>s.time&&s.effects.fire_sale>s.time);assert.equal(await page.locator('#effects img').count(),3);await freeze('powerup-hud');
 await page.evaluate(()=>{const p=kino.debug.getState().player.feet;const id=kino.debug.spawnEnemy([p[0]+100,p[1],p[2]-150]);kino.debug.damageEnemy(id,1);});assert.equal((await state()).kills,1);assert.equal((await state()).points,620);pass('Insta-Kill, Double Points and native timed HUD icons work together');
 await fresh();await page.evaluate(()=>{const p=kino.debug.getState().player.feet;kino.debug.grantScore(2001);kino.debug.spawnEnemy([p[0]+100,p[1],p[2]-150]);kino.debug.spawnEnemy([p[0]-100,p[1],p[2]-150]);kino.debug.dropPowerup('nuke',p);});await step(.1);s=await state();assert.equal(s.enemies.length,0);assert.equal(s.points,2901);assert.equal(s.kills,2);assert((await special()).pickups.length>=1);pass('Nuke clears zombies, awards 400 points without kill bonuses, and preserves native drop eligibility');
 await fresh();await page.evaluate(()=>{kino.debug.setRound(kino.debug.getState().nextDogRound);kino.debug.step(16);});s=await state();assert(s.dogRound);assert.equal(s.enemies.length,s.total);const last=s.enemies.at(-1);await page.evaluate(ids=>{for(const id of ids)kino.debug.damageEnemy(id);kino.debug.step(.05);},s.enemies.map(z=>z.id));drops=(await special()).pickups;assert.equal(drops.length,1);assert.equal(drops[0].type,'full_ammo');assert(Math.hypot(drops[0].position[0]-last.position[0],drops[0].position[2]-last.position[2])<5);pass('Last hellhound leaves one guaranteed Max Ammo at its death position');
 await fresh();await page.evaluate(()=>kino.debug.grantPoints(20000));const box=await station(()=>kino.debug.getEntities().find(e=>e.id===kino.debug.specialState().boxLocation));await page.evaluate(()=>kino.debug.interact());s=await state();assert.equal(s.points,19550);await step(.25);let b=(await special()).boxes.find(b=>b.id===box.id);assert(b.open>0&&b.open<1);const first=b.shown;await step(.4);b=(await special()).boxes.find(b=>b.id===box.id);assert.equal(b.open,1);assert.notEqual(b.shown,first);await page.evaluate(e=>{kino.debug.lookAt([e.position[0]+30,e.position[1]+25,e.position[2]]);},box);await freeze('box-opening');
 await step(3.5);b=(await special()).boxes.find(b=>b.id===box.id);assert(b.roll.ready);assert.equal(b.shown,b.roll.weapon);await freeze('box-offer');assert(await page.evaluate(()=>kino.debug.interact()));if(b.roll.weapon==='zombie_cymbal_monkey')assert.equal((await state()).monkeys,3);else assert.equal((await state()).weapon.id,b.roll.weapon);await step(.6);assert.equal((await special()).boxes.find(b=>b.id===box.id).open,0);pass('Mystery Box opens over 0.5s, cycles weapons, reveals, grants and closes');
 await step(.2);await page.evaluate(()=>kino.debug.interact());await step(17);assert.equal((await special()).boxes.find(b=>b.id===box.id).open,0);assert.equal((await special()).boxes.find(b=>b.id===box.id).roll,null);pass('Untaken box offer sinks away and closes on timeout');
 await fresh();await page.evaluate(()=>{kino.debug.grantPoints(10000);kino.debug.collectPowerup('fire_sale');kino.debug.step(.01);});let specials=await special();assert(specials.fireSale);const ids=specials.boxes.filter(b=>b.id!==specials.boxLocation).slice(0,2).map(b=>b.id);
 for(const id of ids){const e=await page.evaluate(id=>kino.debug.getEntities().find(e=>e.id===id),id);await page.evaluate(e=>{kino.debug.teleportPlayer(e.position);kino.debug.interact();},e);}
 assert.equal((await state()).points,10480);specials=await special();assert.equal(specials.boxes.filter(b=>b.roll).length,2);await step(4);assert((await special()).boxes.filter(b=>b.roll).every(b=>b.roll.ready));pass('Fire Sale activates all nine locations with independent ten-point box rolls');
 await step(22);const e=await page.evaluate(id=>kino.debug.getEntities().find(e=>e.id===id),ids[0]);await page.evaluate(e=>{kino.debug.teleportPlayer(e.position);kino.debug.interact();},e);await step(5);specials=await special();assert(!specials.fireSale);assert(specials.boxes.find(b=>b.id===e.id).roll.ready);assert(await page.evaluate(()=>kino.debug.interact()));pass('An in-progress Fire Sale offer can still be claimed after the sale expires');
 await page.waitForFunction(()=>kino.debug.audioState().played.some(k=>k.endsWith('/music_box_00')));pass('Original Mystery Box music and interaction sounds decode and play');
 await fresh();await page.evaluate(()=>kino.debug.grantPoints(20000));const origin=await station(()=>kino.debug.getEntities().find(e=>e.id===kino.debug.specialState().boxLocation));let teddy=false;
 for(let i=0;i<8;i++){const before=(await state()).points;assert(await page.evaluate(()=>kino.debug.interact()));await step(4);const roll=(await special()).boxes.find(b=>b.id===origin.id).roll;assert(roll?.ready);if(roll.teddy){assert.equal((await state()).points,before);teddy=true;await freeze('box-teddy');await step(5.6);break;}assert(await page.evaluate(()=>kino.debug.interact()));await step(.7);}
 assert(teddy);specials=await special();assert.equal(specials.boxMoves,1);assert.notEqual(specials.boxLocation,origin.id);assert.equal(specials.boxes.find(b=>b.id===origin.id).open,0);pass('Teddy bear appears by the eighth initial pull, refunds the spin and relocates the box');
 await fresh();assert.equal((await special()).pickups.length,0);assert((await special()).boxes.every(b=>!b.roll&&b.open===0));assert.equal((await special()).drink,null);assert.equal(errors.length,0,errors.join('\n'));pass('Restart cleans up pickups, drinks and boxes; browser reports no errors');
}catch(e){console.error(e);checks.push({name:'Failure',passed:false,error:String(e),stack:e.stack,state:await state(),special:await special()});process.exitCode=1;await freeze('failure');}
finally{fs.writeFileSync(out+'/report.json',JSON.stringify({checks,errors},null,2));await browser.close();}
